name: user_repository
description: User Repository
publish_to: none

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  data_provider:
    path: ../data_provider
  storage:
    path: ../storage/storage


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
