name: meno_shop
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  app_ui:
    path: packages/app_ui
  data_provider:
    path: packages/data_provider
  form_inputs:
    path: packages/form_inputs
  storage:
    path: ./packages/storage/storage
  secure_storage:
    path: ./packages/storage/secure_storage
  persistent_storage:
    path: ./packages/storage/persistent_storage
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.3
  dio: ^5.4.1
  equatable: ^2.0.5

  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.3
  hydrated_bloc: ^9.1.4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0
  pinput: ^5.0.0
  envied: ^0.5.4+1
  gap: ^3.0.1
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  turkmen_localization_support: ^0.0.8
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.10+1
  flexi_image_slider: ^1.0.8
  auto_size_text: ^3.0.0
  intl: ^0.18.1
  go_router: ^14.2.1
  rxdart: ^0.28.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_shakemywidget: ^1.0.5+1
  connectivity_plus: ^6.0.5
  flutter_local_notifications: ^17.2.2
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.6.0
dependency_overrides:
  intl: ^0.18.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - packages/app_ui/assets/advantages/ru/
    - packages/app_ui/assets/advantages/tk/
