name: meno_shop
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  app_ui:
    path: packages/app_ui
  data_provider:
    path: packages/data_provider
  form_inputs:
    path: packages/form_inputs
  storage:
    path: ./packages/storage/storage
  secure_storage:
    path: ./packages/storage/secure_storage
  persistent_storage:
    path: ./packages/storage/persistent_storage
  user_repository:
    path: packages/user_repository
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
 
  bloc: ^8.1.3
  custom_pop_up_menu: ^1.2.4
  dio: ^5.4.1
  equatable: ^2.0.5
  flow_builder: ^0.1.0
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  hydrated_bloc: ^9.1.4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  flexi_image_slider: ^1.0.8
  vertical_barchart: ^2.0.0+2
  connectivity_plus: ^6.0.1
  pinput: ^4.0.0
  envied: ^0.5.4+1
  flutter_rating_bar: ^4.0.1
  
  gap: ^3.0.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9

flutter:  
  uses-material-design: true
  assets:
   - assets/