name: secure_storage
description: A Key/Value Secure Storage Client
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  flutter_secure_storage: ^9.0.0
  storage:
    path: ../storage

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.24.0
