name: form_inputs
description: A Dart package which exposes reusable form inputs and validation rules
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  formz: ^0.7.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
