name: app_ui
description: App UI Component Library.
publishh_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.0

  data_provider:
    path: ../data_provider

  flexi_image_slider: ^1.0.8
  flutter:
    sdk: flutter
  flutter_gen: ^5.6.0
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  lints: ^4.0.0
  flutter_gen_runner: ^5.6.0
  build_runner: ^2.4.12

flutter_gen:
  output: lib/src/generated/
  line_length: 80
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true

  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/advantages/
    # - assets/advantages/ru/
    # - assets/advantages/tk/
    - assets/auth/
    - assets/images/
    - assets/language/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
