name: app_ui
description: App UI Component Library.
publishh_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  data_provider:
    path: ../data_provider
  flexi_image_slider: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  horizontal_picker: ^1.2.0
  vertical_barchart: ^2.0.0+2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true  
  assets:
   - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        