name: data_provider
description: A package which handle 3rd layer data from out.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  dio: ^5.4.1
  equatable: ^2.0.5
  hive: ^2.2.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  test: ^1.24.0
