name: data_provider
description: A package which handle 3rd layer data from out.
publish_to: none

environment:
  sdk: ^3.3.0
  
dependencies:
  # user_repository:
    # path: ../user_repository
  dio: ^5.4.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1

  
dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  test: ^1.24.0
