name: persistent_storage
description: Storage that saves data in the device's persistent memory.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  storage:
    path: ../storage

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.24.0
